joint_state_broadcaster:
        ros__parameters:
                type: joint_state_broadcaster/JointStateBroadcaster
                extra_joints:
                        - caster_wheel_joint
                        - caster_base_joint
                        - front_caster_wheel_joint
                        - front_caster_base_joint
                        - tower_joint

joint_velocity_controller:
        ros__parameters:
                type: pid_controller/PidController
                dof_names:
                        - right_wheel_joint
                        - left_wheel_joint
                command_interface: effort
                reference_and_state_interfaces: ["velocity"]
                gains:
                        right_wheel_joint: {p: 1.0, i: 0.5, d: 0.0, i_clamp_max: 100.0, i_clamp_min: -100.0, antiwindup: false}
                        left_wheel_joint: {p: 1.0, i: 0.5, d: 0.0, i_clamp_max: 100.0, i_clamp_min: -100.0, antiwindup: false}
